version: "3.9"

services:
  database:
    image: "mariadb:latest"
    container_name: database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: gift_services
    ports:
      - "3306:3306"
    volumes:
      - gift_services:/var/lib/mysql

volumes:
  gift_services: