version: "3.9"

services:
  api:
    build: .
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - database
    volumes:
      - .:/home/app
    networks:
      - gift

  database:
    image: "mysql:latest"
    container_name: database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: gift_services
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql

    networks:
      gift:
        aliases:
          - database
volumes:
  data:

networks:
  gift:
    external: true
