name: Pipelines
on:
  push:
    branches:
      - action-docker-ci
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Write value to Properties-file
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: './src/main/resources/application.properties'
          property: |
            'spring.datasource.url'
            'spring.datasource.username'
            'spring.datasource.password'
          value: |
            'jdbc:mysql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/gift_services'
            '${{ secrets.DB_USER }}'
            '${{ secrets.DB_PWD }}'
      - name: Deployment
        uses: digitalocean/app_action@main
        with:
          app_name: gift-app
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}