name: Pipelines
on:
  push:
    branches:
      - action-docker-ci
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: ls
      - name: test2
        run: pwd
      - name: Update environment variables
        run: |
              rm src/main/resources/application.properties && touch src/main/resources/application.properties &&
              echo "spring.datasource.url=jdbc:mysql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/gift_services" >> src/main/resources/application.properties && 
              echo "spring.datasource.username=${{ secrets.DB_USER }}" >> src/main/resources/application.properties && 
              echo "spring.datasource.password=${{ secrets.DB_PWD }}" >> src/main/resources/application.properties && 
              echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> src/main/resources/application.properties && 
              echo "spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect" >> src/main/resources/application.properties && 
              echo "spring.jpa.generate-ddl=true" >> src/main/resources/application.properties && 
              echo "spring.jpa.hibernate.ddl-auto=create" >> src/main/resources/application.properties && 
              echo "spring.jpa.show-sql=true" >> src/main/resources/application.properties && 
              echo "spring.jpa.properties.hibernate.format_sql=true" >> src/main/resources/application.properties
      - name: Deployment
        uses: digitalocean/app_action@main
        with:
          app_name: gift-app
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}