name: Pipelines
on:
  push:
    branches:
      - action-docker-ci
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: digitalocean/app_action@main
        with:
          app_name: gift-app
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}