name: Pipelines
on:
  push:
    branches:
      - main
jobs:
  deployment:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: execute
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf gift-services
            git clone git@github.com:Advanced-Programming-Project/gift-services.git
            cd gift-services
            git checkout main
            cp ../config/application.properties ./src/main/resources/application.properties
            docker compose -f docker-compose.ci.yml up -d --build
